name: dotnet-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore dotnetcore-data-ef-cqrs.sln
    - name: Build
      run: dotnet build dotnetcore-data-ef-cqrs.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test dotnetcore-data-ef-cqrs.sln --configuration Release --no-build --verbosity normal
    
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
